create table departmants(
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	department_name varchar(255),
	location varchar(255)
)


create table employees(
    employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name varchar(255),
	last_name varchar(255),
	salary decimal(10,2),
	hire_date date,
	department_id int,CONSTRAINT fk_employees
        FOREIGN KEY (department_id)
        REFERENCES departmants (department_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
)


INSERT INTO employees (employee_id, first_name, last_name, salary, hire_date, department_id) VALUES
(101, 'John', 'Doe', 60000.00, '2021-01-15', 1),
(102, 'Jane', 'Smith', 75000.00, '2020-03-10', 2),
(103, 'Sam', 'Brown', 85000.00, '2019-07-22', 3),
(104, 'Lisa', 'Ray', 62000.00, '2022-09-05', 4),
(105, 'Mike', 'Johnson', 90000.00, '2018-11-30', 5),
(106, 'Sara', 'Connor', 72000.00, '2021-04-18', 1),
(107, 'Chris', 'Evans', 75000.00, '2023-01-01', 5),
(108, 'Maria', 'Garcia', 60000.00, '2022-06-25', 2);

INSERT INTO departmants (department_id, department_name, location) VALUES
-- (1, 'Sales', 'New York'),
-- (2, 'Marketing', 'San Francisco'),
-- (3, 'IT', 'Seattle'),
-- (4, 'HR', 'New York'),
-- (5, 'Engineering', 'Seattle')
(6, 'Medicine', 'India');


-- select and from clause-----

select * from employees
select * from departmants

--where clause ---

select * from departmants
where department_id = 1

select * from employees
where department_id = 1


--where clause with like operator ----

select * from departmants
where department_name like 'S%'

select * from departmants
where department_name like '_T'

select * from employees
where first_name like 'S%'

select * from employees
where first_name like '%a%'

---where clause in AND, OR, Between, In, Not operators ---

select * from departmants
where department_name ='Sales' and location ='New York'

select * from employees
where first_name ='prakash' or last_name ='Smith'

select * from employees
where salary between 60000.00 and 90000.00

select * from departmants
where location in ('New York','Seattle')

select * from departmants
where location not in ('New York','Seattle')

------Group By -------
SELECT count(department_id) as department,location
FROM departmants
GROUP BY location
Order by location

----Having ----
SELECT count(department_id) as department,location
FROM departmants
GROUP BY location
Having count(department_id) > 1
Order by location desc


----Limit -------

select employee_id,first_name,salary from employees
Order by salary
limit 5


----Join-----

  ----Inner Join ----

 select count(a.department_id)as departments, a.location
 from departmants a 
 join employees b on a.department_id = b.department_id
 GROUP BY location
 Having count(a.department_id) > 1

  select a.department_name, a.location, b.first_name as employee_name
 from departmants a 
 join employees b on a.department_id = b.department_id
  where b.salary > 60000.00


 ----Left Join------
 select count(a.department_id)as employees, a.salary
 from employees a 
  left join departmants b on a.department_id = b.department_id 
  GROUP BY a.salary


   select a.department_name, a.location, b.first_name as employee_name
 from departmants a 
  left join employees b on a.department_id = b.department_id 
  where a.department_name != 'Engineering'


  ---Right Join----
     select a.department_id , CONCAT_WS(' ',a.first_name,a.last_name) as full_name,salary
 from employees a 
  right join departmants b on a.department_id = b.department_id 

  
   select count(a.department_id) as total, a.location
 from departmants a 
  right join employees b on a.department_id = b.department_id 
  Group by a.location
  

  ---Full Join----

 -- select a.department_id,a.department_name,b.first_name ,b.salary 
 -- from departmants a 
 -- full join employees b on a.department_id = b.department_id


 
 select count(a.department_id) as total, b.salary as salary
 from departmants a 
 full join employees b on a.department_id = b.department_id
 Group by b.salary
 Having salary >= 75000.00


 ---Cross Join----

 select a.first_name as employee_name,b.department_name
 from employees a
 cross join departmants b
 where a.first_name <> 'Mike'

----Aggregate Function----
SELECT sum(a.salary) as salary,avg(a.salary)::numeric(10,2) as average_salary,b.department_name
FROM employees a
join departmants b on a.department_id = b.department_id
GROUP BY b.department_name

SELECT max(a.salary) as maximum_salary,min(a.salary) as minimum_salary,b.department_name
FROM employees a
join departmants b on a.department_id = b.department_id
GROUP BY b.department_id

----String Function-----

 ----Concate-----
 select CONCAT(first_name,last_name) as full_name,salary
 from employees

 select CONCAT_WS(' ',first_name,last_name) as full_name,salary
 from employees

 ----substring----
 SELECT
    first_name,
    SUBSTRING( last_name, 1, 1 ) AS initial
FROM
    employees
ORDER BY
    first_name;


---replace----

select department_name,replace(location,'New York','Washington')
from departmants


----Reverse----

 select  reverse(CONCAT_WS(' ',first_name,last_name)) as full_name,salary
 from employees


 -------Integer-------

   -----SQRT-------
   select sqrt(salary),first_name from employees

   -----POWER-----
   
    select POWER(2,salary),first_name from employees

	----EXPONENTIAL-----

	select exp(department_id),first_name from employees

	----LOG---------

	select log(exp(department_id)),first_name from employees



------DATE Functions-------

 ----EXTRACTION-----
	
	SELECT TO_CHAR(hire_date, 'Month') 
	FROM employees;
	
	SELECT Date_part('Year',hire_date) 
	FROM employees;
	
	SELECT TO_CHAR(hire_date, 'Day') 
	FROM employees;


 ----DATE Difference----

     SELECT (CURRENT_DATE - hire_date ) AS difference_in_days FROM employees;

	 SELECT Age(CURRENT_DATE ,hire_date ) AS difference_in_days FROM employees;

  ------Formatting Date------
  SELECT TO_CHAR(hire_date, 'DD-MM-YYYY') 
	FROM employees;


  ----ADDS DATE----
  
  SELECT hire_date + INTERVAL '1 year 2 months 5 days' AS new_date FROM employees;
  SELECT (hire_date + INTERVAL '5 days')::date AS new_date FROM employees;



  -----Type Casting-----

  SELECT CAST(salary AS INTEGER) from employees;

  SELECT salary::integer from employees;


 ------Date filter-----
 select * from employees
 where trim(TO_CHAR(hire_date, 'Month'))='March' and Date_part('Year',hire_date)=2020

  










